### ISSUE TITLE
Warning from characteristic "active"

### ISSUE THREAD

**Issue by HackyPaddy** [RaresAil/homebridge-levoit-air-purifier#99]
### Describe The Bug

The plugin works, but the log is flooded with the following error:

`[2.5.2024, 07:34:28] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 07:48:57] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 07:52:22] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 08:51:56] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 09:01:32] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 09:14:41] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`

### Expected behavior

A log without errors :)

### Logs

`[2.5.2024, 07:34:28] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 07:48:57] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 07:52:22] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 08:51:56] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 09:01:32] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[2.5.2024, 09:14:41] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`

### Plugin Config

`
{
            "name": "Levoit Air Luftreiniger",
            "email": "xxx",
            "password": "xxx",
            "platform": "LevoitAirPurifiers"
}
`

### Plugin Version

v3.0.1

### Homebridge Version

v1.8.1

### Node.js Version

v18.19.0

### NPM Version

n/a

### Operating System

Raspberry

**Comment by BastianZim** [comment]
Getting the same error with a Core200

```
[05/05/2024, 12:14:23] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[05/05/2024, 12:14:36] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[05/05/2024, 12:16:40] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[05/05/2024, 12:16:49] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
```

**Comment by ItsHaysus** [comment]
Same issue with 200S

**Comment by jgreenb2** [comment]
Ditto on my core600s running as a child bridge. There are quite a few of these messages polluting the logs which makes debugging   other issues a bit harder. Doesn't seem to affect functionality though.

**Comment by mokolabs** [comment]
I'm also seeing this on the core600s.

**Comment by mcclia40** [comment]
Same for me, child bridge and all.

**Comment by HackyPaddy** [comment]
When will the error be fixed?

**Comment by bchertel** [comment]
core 300s is producing the same log messages

**Comment by Niclassslua** [comment]
Same! Core 200s is also producing this log message:

[10/24/2024, 6:56:04 PM] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[10/24/2024, 6:56:04 PM] [homebridge-levoit-air-purifier] Error: 
    at On.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at On.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2892:12)
    at On.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2410:24)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)

**Comment by HackyPaddy** [comment]
When will the error be fixed?

**Comment by brsexton** [comment]
I am getting these errors every few minutes as well. Do you happen to have any updates on this?

**Comment by 80AAFF** [comment]
I am seeing the same error with a 300s

[29/01/2025, 14:52:48] [homebridge-levoit-air-purifier] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

**Comment by jamesbretz** [comment]
Also getting this message....

**Comment by RicoM77** [comment]
Same here
